---
drupal_install_profile: standard
drupal_enable_modules: []
drupal_account_name: admin
drupal_account_pass: admin
drupal_install_site: false
drupal_build_makefile: false
drupal_makefile_path: /vagrant/drupal.make.yml
