---
- hosts: localhost
  connection: local
  become: yes

  vars_files:
    - beetbox.config.yml
    - project.config.yml
    - vagrant.config.yml
    - local.config.yml

  tasks:

    - name: Create {{ beet_user }} user.
      user:
        name: "{{ beet_user }}"
        shell: /bin/bash
        createhome: yes
        home: "/home/{{ beet_user }}"

    - name: Check for updates.
      git:
        repo: "{{ beet_repo }}"
        dest: "{{ beet_home }}"
        version: "{{ beet_version }}"
        accept_hostkey: yes
        update: yes
        force: yes
      when: beet_keep_updated and (not beet_debug)
