---
- hosts: localhost
  connection: local
  become: yes

  vars_files:
    - config/beetbox.config.yml
    - config/project.config.yml
    - config/vagrant.config.yml
    - config/local.config.yml

  roles:
    - { role: beetbox-init }
    - { role: beetbox-known-hosts, when: known_hosts }
    - { role: beetbox-common }
    - { role: beetbox-drupal, when: beet_project == 'drupal' }
    - { role: beetboxvm.backdrop, when: beet_project == 'backdrop' }
    - { role: beetboxvm.cakephp, when: beet_project == 'cakephp' }
    - { role: beetboxvm.concrete5, when: beet_project == 'concrete5' }
    - { role: beetboxvm.kohana, when: beet_project == 'kohana' }
    - { role: beetboxvm.modx, when: beet_project == 'modx' }
    - { role: beetboxvm.silverstripe, when: beet_project == 'silverstripe' }
    - { role: beetboxvm.slim, when: beet_project == 'slim' }
    - { role: beetboxvm.wordpress, when: beet_project == 'wordpress' }
    - { role: beetbox-packages }
    - { role: beetbox-web }
    - { role: beetbox-apparmor }
    - { role: beetbox-symlinks, when: symlinks }
    - { role: beetbox-php-nginx }
    - { role: beetbox-welcome }
