---
- name: Ensure necessary groups exist.
  group: "name={{ item }} state=present"
  with_items:
    - admin
    - dialout

- name: Ensure {{ beet_user }} user is in admin group.
  user:
    name: "{{ beet_user }}"
    append: yes
    groups: "admin"

- name: Ensure vagrant home directory is present.
  file:
    path: "/home/{{ beet_user }}/"
    state: directory
    owner: "{{ beet_user }}"
    group: "{{ beet_user }}"
    recurse: true

- name: Ensure www-data user is in dialout group.
  user:
    name: "www-data"
    append: yes
    groups: "dialout"

- name: Set nicer permissions on Apache log directory.
  file:
    path: "/var/log/{{ apache_daemon }}"
    state: directory
    mode: 0755
    recurse: true

- name: Check for default nginx vhosts.
  stat: "path={{ nginx_vhost_path }}//{{ beet_domain }}.conf"
  register: nginx_default_vhost_conf

- name: Copy default Nginx vhosts into place.
  template:
    src: ../templates/nginx-vhost.conf.j2
    dest: "{{ nginx_vhost_path }}/{{ item.server_name }}.conf"
    force: yes
    owner: root
    group: root
    mode: 0644
  with_items: nginx_hosts
  notify: restart nginx
  when: not nginx_default_vhost_conf.stat.exists
