---
- name: Check if site is already installed.
  shell: >
    ./core/scripts/backdrop.sh http://default/
    chdir={{ beet_root }}
  register: backdrop_site_installed
  failed_when: false
  changed_when: false

- name: Install Backdrop.
  shell: >
    ./core/scripts/install.sh {{ backdrop_install_profile | default('standard') }}
    --site-name="{{ beet_site_name }}"
    --account-name={{ backdrop_account_name }}
    --account-pass={{ backdrop_account_pass }}
    --db-url=mysql://{{ beet_mysql_user }}:{{ beet_mysql_password }}@localhost/{{ beet_mysql_database }}
    chdir={{ beet_root }}
  notify: restart webserver
  changed_when: "backdrop_site_installed.stdout == ''"
  failed_when: false
