---
# Beetbox config.
beetbox_project: drupal
beetbox_keep_updated: no
ansible_debug: no
beetbox_domain: "beetbox.local"
beetbox_docroot: "/www"
beetbox_site_name: "Beetbox"

# Ansible Galaxy roles
galaxy_roles:
  - { name: arknoll.selenium }
  - { name: geerlingguy.adminer }
  - { name: geerlingguy.apache }
  - { name: geerlingguy.composer }
  - { name: geerlingguy.daemonize }
  - { name: geerlingguy.drupal-console }
  - { name: geerlingguy.drush }
  - { name: geerlingguy.firewall }
  - { name: geerlingguy.git }
  - { name: geerlingguy.java }
  - { name: geerlingguy.mailhog }
  - { name: geerlingguy.memcached }
  - { name: geerlingguy.mysql }
  - { name: geerlingguy.nginx }
  - { name: geerlingguy.nodejs }
  - { name: geerlingguy.php }
  - { name: geerlingguy.php-memcached }
  - { name: geerlingguy.php-mysql }
  - { name: geerlingguy.php-pecl }
  - { name: geerlingguy.php-redis }
  - { name: geerlingguy.php-xdebug }
  - { name: geerlingguy.php-xhprof }
  - { name: geerlingguy.pimpmylog }
  - { name: geerlingguy.postfix }
  - { name: geerlingguy.redis }
  - { name: geerlingguy.ruby }
  - { name: geerlingguy.security }
  - { name: geerlingguy.solr }
  - { name: geerlingguy.varnish }
  - { name: heskethm.wp-cli }

# Drupal settings
drupal_install_profile: standard
drupal_enable_modules: []
drupal_account_name: admin
drupal_account_pass: admin

# Drush site install
drupal_install_site: false

# Make file config
drupal_build_makefile: false
drupal_makefile_path: /vagrant/drupal.make.yml

# Wordpress settings
wp_account_name: admin
wp_account_pass: admin
wp_account_email: admin@beetbox.local
wp_download_core: no
wp_locale: ''
wp_install_site: no

# Symlinks
symlinks: no

# Apache config.
apache_vhosts:
  - servername: "{{ beetbox_domain }}"
    documentroot: "{{ beebox_docroot }}"
apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load

# Databases
beetbox_mysql_user: beetbox
beetbox_mysql_password: beetbox
beetbox_mysql_database: beetbox
mysql_databases:
  - name: "{{ beetbox_mysql_database }}"
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: "{{ beetbox_mysql_user }}"
    host: "%"
    password: "{{ beetbox_mysql_password }}"
    priv: "{{ beetbox_mysql_database }}.*:ALL"

# Comment out any extra utilities you don't want to install.
installed_extras:
  - adminer
  - mailhog
  - memcached
  - xdebug
  - xhprof
  - selenium
  - drupal-console
  # - varnish
  # - pimpmylog
  # - nginx
  # - nodejs
  # - ruby
  # - solr
  # - redis

# Add any extra packages you'd like to install.
extra_packages:
  - imagemagick
  - unzip

# Firewall config
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
firewall_log_dropped_packets: false

# Varnish config
varnish_listen_port: 81
varnish_storage: "malloc,256m"

# Nodejs config
nodejs_version: "0.12"
nodejs_npm_global_packages: []

# Ruby config
ruby_install_gems: []

# Apache config
apache_remove_default_vhost: true
apache_listen_port: 80
apache_vhosts:
  - servername: "beetbox.local"
    documentroot: "/drupal"

# Nginx config.
nginx_php_fpm: /var/run/php5-fpm.sock

# PHP config
php_version: "5.6"
php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_enable_php_fpm: 1
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"

# Composer config
composer_path: /usr/bin/composer
composer_home_path: '/home/vagrant/.composer'
# composer_global_packages:
#   - { name: phpunit/phpunit, release: '@stable' }

# Drush config
drush_version: "8.0.0-rc4"
drush_composer_cli_options: "--prefer-dist --no-interaction"

# MySQL Config
mysql_root_password: root
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_install_filename: index.php

# XDebug config.
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 1
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256

# Solr config.
solr_version: "4.10.4"
solr_xms: "64M"
solr_xmx: "128M"

# Selenium config.
selenium_version: 2.46.0

# Other config.
known_hosts_path: ~/.ssh/known_hosts
