---
# Ansible Galaxy roles
galaxy_roles:
  - arknoll.selenium
  - geerlingguy.adminer
  - geerlingguy.apache
  - geerlingguy.composer
  - geerlingguy.daemonize
  - geerlingguy.drupal-console
  - geerlingguy.drush
  - geerlingguy.firewall
  - geerlingguy.git
  - geerlingguy.java
  - geerlingguy.mailhog
  - geerlingguy.memcached
  - geerlingguy.mysql
  - geerlingguy.nginx
  - geerlingguy.nodejs
  - geerlingguy.php
  - geerlingguy.php-memcached
  - geerlingguy.php-mysql
  - geerlingguy.php-pecl
  - geerlingguy.php-xdebug
  - geerlingguy.php-xhprof
  - geerlingguy.pimpmylog
  - geerlingguy.postfix
  - geerlingguy.repo-remi
  - geerlingguy.ruby
  - geerlingguy.security
  - geerlingguy.solr
  - geerlingguy.varnish

# Drupal settings
drupal_domain: "beetbox.local"
drupal_core_path: "/drupal"
drupal_site_name: "Beetbox"
drupal_install_profile: standard
drupal_enable_modules: []
drupal_account_name: admin
drupal_account_pass: admin
drupal_mysql_user: drupal
drupal_mysql_password: drupal
drupal_mysql_database: beetbox

# Drush site install
install_site: false

# Make file config
build_makefile: false
drush_makefile_path: /vagrant/drupal.make.yml

# Symlinks
symlinks: no

# Apache config.
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load

# Databases
mysql_databases:
  - name: "{{ drupal_mysql_database }}"
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: "{{ drupal_mysql_user }}"
    host: "%"
    password: "{{ drupal_mysql_password }}"
    priv: "{{ drupal_mysql_database }}.*:ALL"

# Comment out any extra utilities you don't want to install.
installed_extras:
  - adminer
  - mailhog
  - memcached
  - pimpmylog
  - varnish
  - xdebug
  - xhprof
  - selenium
  - drupal-console
  # - nginx
  # - nodejs
  # - ruby
  # - solr

# Add any extra packages you'd like to install.
extra_packages:
  - imagemagick
  - unzip

# Firewall config
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
firewall_log_dropped_packets: false

# Varnish config
varnish_listen_port: 81
varnish_storage: "malloc,256m"

# Nodejs config
nodejs_version: "0.12"
nodejs_npm_global_packages: []

# Ruby config
ruby_install_gems: []

# Apache config
apache_remove_default_vhost: true
apache_listen_port: 80
apache_vhosts:
  - servername: "beetbox.local"
    documentroot: "/drupal"

# PHP config
php_version: "5.6"
php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_enable_php_fpm: 1
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"

# Composer config
composer_path: /usr/bin/composer
composer_home_path: '/home/vagrant/.composer'
# composer_global_packages:
#   - { name: phpunit/phpunit, release: '@stable' }

# Drush config
drush_version: "8.0.0-rc4"
drush_composer_cli_options: "--prefer-dist --no-interaction"

# MySQL Config
mysql_root_password: root
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_install_filename: index.php

# XDebug config.
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 1
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256

# Solr config.
solr_version: "4.10.4"
solr_xms: "64M"
solr_xmx: "128M"

# Selenium config.
selenium_version: 2.46.0

# Other config.
known_hosts_path: ~/.ssh/known_hosts
