---
- hosts: localhost
  connection: local
  user: root
  become: yes

  vars_files:
    - beetbox.config.yml
    - project.config.yml
    - vagrant.config.yml
    - local.config.yml

  tasks:

    - name: Create vagrant user.
      user:
        name: vagrant
        shell: /bin/bash

    - name: Check for updates.
      git:
        repo: "{{ beetbox_repo }}"
        dest: "{{ beetbox_home }}"
        accept_hostkey: yes
        update: yes
        force: yes
      when: beetbox_keep_updated and (not beetbox_debug)

    - name: Set ownership of beetbox directory.
      file:
        path: "{{ beetbox_home }}"
        owner: vagrant
        group: vagrant
        recurse: yes
        state: directory
      when: (not beetbox_debug)

    - name: Install Galaxy roles
      command: >
        ansible-galaxy install {{ item.name }} -p {{ beetbox_role_dir }}
        creates={{ beetbox_role_dir }}/{{ item.name }}/meta/main.yml
      with_items: galaxy_roles

    - name: Update Galaxy roles
      command: >
        ansible-galaxy install {{ item.name }} -p {{ beetbox_role_dir }} --force --ignore-errors
      when: item.force_update is defined
      with_items: galaxy_roles
