---
- hosts: localhost
  connection: local
  become: yes

  vars_files:
    - beetbox.config.yml
    - project.config.yml
    - vagrant.config.yml
    - local.config.yml

  roles:
    - { role: beetbox-tests, when: beet_run_tests }
