---
- hosts: localhost
  connection: local
  user: root
  become: yes

  vars_files:
    - beetbox.config.yml
    - project.config.yml
    - vagrant.config.yml
    - local.config.yml

  pre_tasks:
    - include: tasks/init-debian.yml

  roles:
    - { role: beetbox-common }
    - { role: beetbox-backdrop, when: beetbox_project == 'backdrop' }
    - { role: beetbox-drupal, when: beetbox_project == 'drupal' }
    - { role: beetbox-silverstripe, when: beetbox_project == 'silverstripe' }
    - { role: beetbox-wordpress, when: beetbox_project == 'wordpress' }

  tasks:
    - include: tasks/extras.yml
    - include: tasks/www.yml
    - include: tasks/apparmor.yml

    # Create symlinks.
    - include: tasks/create-symlinks.yml
      when: symlinks
