---
- hosts: localhost
  connection: local
  user: root
  become: yes

  vars_files:
    - beetbox.config.yml
    - project.config.yml
    - vagrant.config.yml
    - local.config.yml

  vars:
    role_dir: /ansible/roles

  tasks:

    - name: Install Galaxy roles
      command: >
        ansible-galaxy install {{ item }} -p {{ role_dir }}
        creates={{ role_dir }}/{{ item }}/tasks/main.yml
      with_items: galaxy_roles
