---
- hosts: localhost
  connection: local
  user: root
  become: yes

  vars_files:
    - beetbox.config.yml
    - project.config.yml
    - vagrant.config.yml
    - local.config.yml

  vars:
    beetbox_repo: https://github.com/DrupalMel/beetbox.git
    beetbox_home: /beetbox
    role_dir: roles

  tasks:

    - name: Check for updates.
      git:
        repo: "{{ beetbox_repo }}"
        dest: "{{ beetbox_home }}"
        accept_hostkey: yes
        update: yes
        force: yes
      when: beetbox_keep_updated and (not ansible_debug)

    - name: Set ownership of beetbox directory.
      file:
        path: "{{ beetbox_home }}"
        owner: vagrant
        group: vagrant
        recurse: yes
        state: directory
      when: (not ansible_debug)

    - name: Install Galaxy roles
      command: >
        ansible-galaxy install {{ item.name }} -p {{ role_dir }}
        creates={{ role_dir }}/{{ item.name }}/meta/main.yml
      with_items: galaxy_roles

    - name: Update Galaxy roles
      command: >
        ansible-galaxy install {{ item.name }} -p {{ role_dir }} --force --ignore-errors
      when: item.force_update is defined
      with_items: galaxy_roles
