---
- name: Generate Drupal site with drush makefile.
  command: >
    {{ drush_path }} make -y {{ drupal_makefile_path }} --no-gitinfofile
    chdir={{ beet_root }}
  when: not drupal_site.stat.exists
